"""The clock action's external portal operations, isolated for fake testing."""

from datetime import time
from typing import Any, Callable, Protocol


class ClockPortalPort(Protocol):
    def login(self, driver: Any, wait: Any, username: str, password: str) -> None: ...

    def read_swipes(self, driver: Any, wait: Any, get_loc: Callable) -> tuple: ...

    def select_action(self, driver: Any, wait: Any, locator: tuple) -> None: ...

    def handle_health(self, driver: Any, wait: Any, get_loc: Callable) -> None: ...

    def execute_button(self, wait: Any, locator: tuple) -> Any: ...

    def highlight(self, driver: Any, button: Any) -> None: ...

    def submit(self, driver: Any, button: Any) -> None: ...

    def accept_alert(self, driver: Any) -> None: ...

    def verify(self, driver: Any, get_loc: Callable, act_name: str,
               check_start: time, check_end: time, username: str) -> bool: ...
